services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: payouts
      POSTGRES_USER: payouts
      POSTGRES_PASSWORD: payouts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    working_dir: /app/src
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret"
      POSTGRES_DB: payouts
      POSTGRES_USER: payouts
      POSTGRES_PASSWORD: payouts
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      PYTHONPATH: /app/src
      DJANGO_SETTINGS_MODULE: config.settings
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"

  worker:
    build: .
    working_dir: /app/src
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret"
      POSTGRES_DB: payouts
      POSTGRES_USER: payouts
      POSTGRES_PASSWORD: payouts
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      PYTHONPATH: /app/src
      DJANGO_SETTINGS_MODULE: config.settings

    depends_on:
      - db
      - redis
    command: celery -A config worker -l info

volumes:
  pgdata:
